scripts: "/home/lgold/phd/research/projects/landscape_analysis/fl_analysis/scripts/"
csv_input: "test_landscape.csv"
csv_delimiter: ","

walk_type:
  - uniform

random_seed: 312123

adaptive_walk_params:
  starting_set_size: 1
  sample_size: 10
