scripts: "/home/lgold/phd/research/projects/landscape_analysis/fl_analysis/scripts/"
csv_input: "../../data/CRP_FIS_Library.csv"
csv_delimiter: "\t"

csv_phenotype_prefix: score.

phenotypes:
  - CRP
  - Fis

non_param_walks:
  - greedy
  - uniform

param_walks:
  - kimura

pop_size_exp:
  - 2
  - 5
  - 8

random_seed: 312123

adaptive_walk_params:
  starting_set_size: 10
  sample_size: 10
